<?php
return [
    'email' => [
        'global' => [
            'title' => 'Global Email',
            'params' => ['name' => 'Will replace by user name', 'message' => 'Original Message'],
            'content' => 'Hello [name], [message]'
        ],
        'verify' => [
            'title' => 'Email Verification OTP',
            'params' => ['name' => 'Will replace by user name', 'otp' => 'Verification OTP'],
            'content' => 'Hello [name], Your email verification OTP is [otp]'
        ],
        'reset_password' => [
            'title' => 'Password Reset OTP',
            'params' => ['name' => 'Will replace by user name', 'otp' => 'Password Reset OTP OTP'],
            'content' => 'Hello [name], Your password reset OTP is [otp]'
        ],
        'new_order' => [
            'title' => 'Order Placed Successfully',
            'params' => [
                'id' => 'Order ID',
                'coupon_code' => 'Coupon Code',
                'discount' => 'Applied Discount',
                'shipping_cost' => 'Applied Shipping Charge',
                'status' => 'Order Status. pending|processing|on the way|delivered|hold|canceled',
                'created_at' => 'Order Creating Time. Format: M d, Y h:i a',
                'net_total' => 'Order Items Subtotal',
                // 'tax_total' => 'Total Tax Amount',
                'gross_total' => 'Order Total Amount, Coupon & Others',
                // 'gross_total' => 'Order Total Amount After Tax, Coupon & Others',
                'payment_trx' => 'Payment Transaction ID',
                'payment_status' => 'Order Payment Status',
                'payment_method' => 'Payment Gateway Name',
                'items' => 'Renders Order Items Table With Quantity & Price',
                'shipping.name' => 'Order shipping name',
                'shipping.email' => 'Order shipping email',
                'shipping.phone' => 'Order shipping phone',
                'shipping.formatted_country' => 'Order shipping country',
                'shipping.formatted_state' => 'Order shipping state',
                'shipping.city' => 'Order shipping city',
                'shipping.line1' => 'Order shipping street address line one',
                'shipping.line2' => 'Order shipping street address line two',
                'download_link' => 'Invoice Preview Link Online',
                'preview_link' => 'Invoice Preview Link Online',
            ],
            'content' => 'Hello [shipping.name], order successfully placed. Order ID #[id]'
        ],
        'order_updated' => [
            'title' => 'Order Updated Successfully',
            'params' => [
                'id' => 'Order ID',
                'coupon_code' => 'Coupon Code',
                'discount' => 'Applied Discount',
                'shipping_cost' => 'Applied Shipping Charge',
                'status' => 'Order Status. pending|processing|on the way|delivered|hold|canceled',
                'created_at' => 'Order Creating Time. Format: M d, Y h:i a',
                'net_total' => 'Order Items Subtotal',
                // 'tax_total' => 'Total Tax Amount',
                'gross_total' => 'Order Total Amount, Coupon & Others',
                // 'gross_total' => 'Order Total Amount After Tax, Coupon & Others',
                'payment_trx' => 'Payment Transaction ID',
                'payment_status' => 'Order Payment Status',
                'payment_method' => 'Payment Gateway Name',
                'items' => 'Renders Order Items Table With Quantity & Price',
                'shipping.name' => 'Order shipping name',
                'shipping.email' => 'Order shipping email',
                'shipping.phone' => 'Order shipping phone',
                'shipping.formatted_country' => 'Order shipping country',
                'shipping.formatted_state' => 'Order shipping state',
                'shipping.city' => 'Order shipping city',
                'shipping.line1' => 'Order shipping street address line one',
                'shipping.line2' => 'Order shipping street address line two',
                'download_link' => 'Invoice Preview Link Online',
                'preview_link' => 'Invoice Preview Link Online',
            ],
            'content' => 'Hello [shipping.name], your order marked as [status_string]. Order ID #[id]'
        ],
        'invoice' => [
            'title' => 'Order Invoice #[id]',
            'params' => [
                'id' => 'Order ID',
                'coupon_code' => 'Coupon Code',
                'discount' => 'Applied Discount',
                'shipping_cost' => 'Applied Shipping Charge',
                'status' => 'Order Status. pending|processing|on the way|delivered|hold|canceled',
                'created_at' => 'Order Creating Time. Format: M d, Y h:i a',
                'net_total' => 'Order Items Subtotal',
                // 'tax_total' => 'Total Tax Amount',
                'gross_total' => 'Order Total Amount, Coupon & Others',
                // 'gross_total' => 'Order Total Amount After Tax, Coupon & Others',
                'payment_trx' => 'Payment Transaction ID',
                'payment_status' => 'Order Payment Status',
                'payment_method' => 'Payment Gateway Name',
                'items' => 'Renders Order Items Table With Quantity & Price',
                'shipping.name' => 'Order shipping name',
                'shipping.email' => 'Order shipping email',
                'shipping.phone' => 'Order shipping phone',
                'shipping.formatted_country' => 'Order shipping country',
                'shipping.formatted_state' => 'Order shipping state',
                'shipping.city' => 'Order shipping city',
                'shipping.line1' => 'Order shipping street address line one',
                'shipping.line2' => 'Order shipping street address line two',
                'download_link' => 'Invoice Preview Link Online',
                'preview_link' => 'Invoice Preview Link Online',
            ],
            'content' => file_get_contents(resource_path('default_invoice.txt'))
        ],
        'ref_link' => [
            'title' => 'Join Me In ScentQ',
            'params' => [
                'first_name' => 'Sender first name',
                'last_name' => 'Sender last name',
                'link' => 'Referral Link',
                'recipient_email' => 'Recipient Email'
            ],
            'content' => 'Hey buddy, I\'m [first_name] [last_name]. Come and join with me in ScentQ with this link and claim free fragrance. <a href="[link]">Join Me</a>'
        ],
        'order_delivered' => [
            'title' => 'How was your delivery',
            'params' => [
                'id' => 'Order ID',
                'coupon_code' => 'Coupon Code',
                'discount' => 'Applied Discount',
                'shipping_cost' => 'Applied Shipping Charge',
                'status' => 'Order Status. pending|processing|on the way|delivered|hold|canceled',
                'created_at' => 'Order Creating Time. Format: M d, Y h:i a',
                'net_total' => 'Order Items Subtotal',
                // 'tax_total' => 'Total Tax Amount',
                // 'gross_total' => 'Order Total Amount After Tax, Coupon & Others',
                'gross_total' => 'Order Total Amount, Coupon & Others',
                'payment_trx' => 'Payment Transaction ID',
                'payment_status' => 'Order Payment Status',
                'payment_method' => 'Payment Gateway Name',
                'items' => 'Renders Order Items Table With Quantity & Price',
                'shipping.name' => 'Order shipping name',
                'shipping.email' => 'Order shipping email',
                'shipping.phone' => 'Order shipping phone',
                'shipping.formatted_country' => 'Order shipping country',
                'shipping.formatted_state' => 'Order shipping state',
                'shipping.city' => 'Order shipping city',
                'shipping.line1' => 'Order shipping street address line one',
                'shipping.line2' => 'Order shipping street address line two',
                'download_link' => 'Invoice Preview Link Online',
                'preview_link' => 'Invoice Preview Link Online',
            ],
            'content' => 'Hello [shipping.name], order successfully delivered. Order ID #[id]'
        ],
        'order_canceled' => [
            'title' => 'Your order has been cancelled',
            'params' => [
                'id' => 'Order ID',
                'coupon_code' => 'Coupon Code',
                'discount' => 'Applied Discount',
                'shipping_cost' => 'Applied Shipping Charge',
                'status' => 'Order Status. pending|processing|on the way|delivered|hold|canceled',
                'created_at' => 'Order Creating Time. Format: M d, Y h:i a',
                'net_total' => 'Order Items Subtotal',
                // 'tax_total' => 'Total Tax Amount',
                'gross_total' => 'Order Total Amount, Coupon & Others',
                // 'gross_total' => 'Order Total Amount After Tax, Coupon & Others',
                'payment_trx' => 'Payment Transaction ID',
                'payment_status' => 'Order Payment Status',
                'payment_method' => 'Payment Gateway Name',
                'items' => 'Renders Order Items Table With Quantity & Price',
                'shipping.name' => 'Order shipping name',
                'shipping.email' => 'Order shipping email',
                'shipping.phone' => 'Order shipping phone',
                'shipping.formatted_country' => 'Order shipping country',
                'shipping.formatted_state' => 'Order shipping state',
                'shipping.city' => 'Order shipping city',
                'shipping.line1' => 'Order shipping street address line one',
                'shipping.line2' => 'Order shipping street address line two',
                'download_link' => 'Invoice Preview Link Online',
                'preview_link' => 'Invoice Preview Link Online',
            ],
            'content' => 'Hello [shipping.name], your order has been cancelled - Order ID #[id]'
        ],
        'broadcast' => [
            'title' => '[title]',
            'params' => [
                'title' => 'Campaign Title',
                'content' => 'Campaign Content Or Body',
                'name' => 'User full name'
            ],
            'content' => '[content]'
        ]
    ]
];
